stage: build
image:
  name: docker:24.0.5
  pull_policy: if-not-present
services:
  - name: docker:24.0.5-dind
    pull_policy: if-not-present
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
script:
  - apk add --no-cache git
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use --driver-opt network=host
  - docker buildx build --platform linux/amd64,linux/arm64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --push .
